version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: ai-direksi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_direksi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-direksi-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-direksi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_direksi
    depends_on:
      - db
    networks:
      - ai-direksi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-direksi-frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ai-direksi-network

volumes:
  postgres_data:

networks:
  ai-direksi-network:
    driver: bridge
